### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by icanzilb**
It looked like a typo in the read me

### CODE REVIEW

**Comment by HBehrens** [comment]
Thanks, Marin. Actually, this sample is a bit outdated. Did you see https://github.com/BeamApp/Transit/wiki/Internals ? There are some more conceptual ideas.

**Comment by icanzilb** [comment]
That looks better :] you should definitely link it from the README

**Comment by HBehrens** [comment]
Actually, it is. Way at the bottom...

**Comment by icanzilb** [comment]
I noticed "android" down there and looked away - my bad

**Pull request merged**
